# Generated by Django 3.1.2 on 2020-11-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.persona')),
                ('FechaRegistro', models.DateTimeField()),
            ],
            bases=('polls.persona',),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=150)),
                ('calle_colindancia', models.CharField(max_length=150)),
                ('colinia', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_final', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.persona')),
                ('descripcion_trabajador', models.CharField(max_length=150)),
                ('telefono_fijo', models.CharField(max_length=10)),
            ],
            bases=('polls.persona',),
        ),
        migrations.CreateModel(
            name='Trato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(max_length=10)),
                ('fecha_termino', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('trato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.trato')),
                ('comentario', models.CharField(max_length=150)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_solicitud', models.CharField(max_length=150)),
                ('imagen_solicitud', models.ImageField(upload_to='')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.consumidor')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.CharField(max_length=150)),
                ('precio_promedio', models.CharField(max_length=50)),
                ('trabajadores', models.ManyToManyField(to='polls.Trabajador')),
            ],
        ),
    ]
